#!/bin/bash

if [ $# -le 0 ]; then
    echo "Specify the compiler to use: "
    read COMPILER
else
    COMPILER=$1
fi
if [ $# -le 1 ]; then
    echo "Specify the executable c file, without including the .c: "
    read SOURCE
else
    SOURCE=$2
fi
if [ $# -le 2 ]; then
    echo "Specify the name of the makefile being created: "
    read MAKEFILE
else
    MAKEFILE=$3
fi
if [ $# -gt 3 ]; then
    echo "Please call makeMake with 3 parameters, not more."    
fi

touch $MAKEFILE
echo -e "#Generated makefile with makeMake. Last updated $(date)\n" > "$MAKEFILE"

#add OS identification
echo -e "OS := \$(shell uname -s)\n" >> "$MAKEFILE"
echo -e "ifeq (\$(OS), Darwin)" >> "$MAKEFILE"
echo -e "\tINCLUDE_PATH := /opt/homebrew/Cellar/criterion/2.4.1_1/include" >> "$MAKEFILE"
echo -e "\tLIB_PATH := /opt/homebrew/Cellar/criterion/2.4.1_1/lib" >> "$MAKEFILE"
echo -e "\tCC = $COMPILER-12" >> "$MAKEFILE"
echo "endif" >> "$MAKEFILE"
echo "ifeq (\$(OS), Linux)" >> "$MAKEFILE"
echo -e "\tINCLUDE_PATH := /util/criterion/include" >> "$MAKEFILE"
echo -e "\tLIB_PATH := /util/criterion/lib/x86_64-linux-gnu" >> "$MAKEFILE"
echo -e "\tCC = $COMPILER" >> "$MAKEFILE"
echo -e "endif\n" >> "$MAKEFILE"


CFLAGS="-Wall -std=c11"
echo -e "# Variables used by makefile\n" >> "$MAKEFILE"
echo "CC=$COMPILER" >> "$MAKEFILE"
echo "CFLAGS=$CFLAGS" >> "$MAKEFILE"
echo "SRC=$SOURCE" >> "$MAKEFILE"
OBJECTS=
for sourceFile in $(ls *.c)
do		  
    if [ "$sourceFile" != "$SOURCE.c" ]; then
	BASE=${sourceFile%.c}
	OBJECTS="$BASE.o $OBJECTS"
    fi
done
echo -e "OBJECTS=$OBJECTS\n" >> "$MAKEFILE"		  		  

echo -e "# Recipes for targets\n" >> "$MAKEFILE"
#do the rules here
for file in $(ls *.c)
do
    if [ "$file" != "$SOURCE.c" ]; then
	echo -e "`$COMPILER -MM $file`" >> "$MAKEFILE"
	echo -e "\t\$(CC) \$(CFLAGS) -c $file\n" >> "$MAKEFILE"
    fi
done
echo -e "$SOURCE: \$(OBJECTS)" >> "$MAKEFILE"
echo -e "\t\$(CC) -o \$(SRC) \$(OBJECTS) \$(SRC).c\n" >> "$MAKEFILE"

echo -e "# PHONY targets\n" >> "$MAKEFILE"
echo ".PHONY: clean" >> "$MAKEFILE"
echo "clean:" >> "$MAKEFILE"
echo -e "\trm -rf *~ \$(OBJECTS) \$(SRC)\n" >> "$MAKEFILE"
echo "# End of makefile" >> "$MAKEFILE"
  

